# Generated by Django 2.2.2 on 2020-04-19 15:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import events.models
import events.validators
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=500, verbose_name='Заголовок События')),
                ('imageOld', models.ImageField(default='', upload_to=events.models.Event.user_directory_path, validators=[events.validators.validate_image], verbose_name='Картинка к событию')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '390x280', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name='Выберите область')),
                ('imageBig', image_cropping.fields.ImageRatioField('imageOld', '900x315', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки в большом варианте', hide_image_field=False, size_warning=True, verbose_name='Большая картинка')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Место проведения')),
                ('map', models.CharField(blank=True, default='', max_length=1501, verbose_name='Ссылка на яндекс-карту')),
                ('dateStart', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала')),
                ('dateEnd', models.DateField(blank=True, null=True, verbose_name='Дата окончания/проведения(ОСТАВЬТЕ ПУСТЫМ, ЕСЛИ У ВОЗМОЖНОСТИ НЕТ ПЕРИОДА ПРОВЕДЕНИЯ)')),
                ('date', models.CharField(default='', max_length=100, verbose_name='Строковое представление даты')),
                ('main', models.BooleanField(default=False, verbose_name='Отображение на главной странице')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('directions', models.ManyToManyField(blank=True, to='directions.Direction', verbose_name='Выберите Тэги')),
            ],
            options={
                'verbose_name': 'Событие',
                'ordering': ['dateStart', 'dateEnd'],
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='events_even_title_aedf91_idx'),
        ),
    ]
