# Generated by Django 2.2.2 on 2020-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['text'], name='events_even_text_078e4e_idx'),
        ),
    ]
