# Generated by Django 2.2.2 on 2020-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200419_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.Direction', verbose_name='Тэги'),
        ),
    ]
