# Generated by Django 2.2.2 on 2020-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200420_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания/проведения(ОСТАВЬТЕ ПУСТЫМ, ЕСЛИ У СОБЫТИЯ НЕТ ПЕРИОДА ПРОВЕДЕНИЯ)'),
        ),
    ]
