# Generated by Django 2.2.2 on 2020-04-17 12:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import image_cropping.fields
import news.models
import news.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=400, verbose_name='Заголовок Новости')),
                ('preview', models.TextField(blank=True, default='', max_length=500, verbose_name='Превью Новости')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и Время')),
                ('imageOld', models.ImageField(default='', upload_to=news.models.News.user_directory_path, validators=[news.validators.validate_image], verbose_name='Картинка к новости')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки в маленьком варианте', hide_image_field=False, size_warning=True, verbose_name='Маленькая картинка')),
                ('imageBig', image_cropping.fields.ImageRatioField('imageOld', '900x315', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки в большом варианте', hide_image_field=False, size_warning=True, verbose_name='Большая картинка')),
                ('main', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('important', models.BooleanField(default=False, verbose_name='Важная новость')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['preview'], name='news_news_preview_99323f_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='news_news_title_ef31ad_idx'),
        ),
    ]
