# Generated by Django 2.2.2 on 2020-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.Direction', verbose_name='Выберите Направления'),
        ),
    ]
