# Generated by Django 2.2.2 on 2020-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_directions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['text'], name='news_news_text_b4a010_idx'),
        ),
    ]
