# Generated by Django 2.2.2 on 2020-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200419_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.Direction', verbose_name='Тэги'),
        ),
    ]
