# Generated by Django 2.2.2 on 2020-04-17 12:45

import ckeditor.fields
import directions.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, unique=True, verbose_name='Название тэга')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Тэги',
                'verbose_name': 'Тэг',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, unique=True, verbose_name='Название направления')),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Текст')),
                ('imageInactive', models.ImageField(blank=True, default='', upload_to='trends/', validators=[directions.validators.validate_image], verbose_name='Картинка неактивная')),
                ('imageActive', models.ImageField(blank=True, default='', upload_to='trends/', validators=[directions.validators.validate_image], verbose_name='Картинка при наведении')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Направления',
                'verbose_name': 'Направление',
            },
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['title'], name='directions__title_7ce066_idx'),
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['text'], name='directions__text_12c499_idx'),
        ),
        migrations.AddField(
            model_name='direction',
            name='id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.Trend'),
        ),
    ]
