# Generated by Django 2.2.2 on 2020-04-23 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата матча'),
        ),
    ]
