# Generated by Django 2.2.2 on 2020-04-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20200423_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Team', verbose_name='Чемпион'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Rules', verbose_name='Правила'),
        ),
    ]
