# Generated by Django 2.2.2 on 2020-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['customOrder'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='customOrder',
            field=models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место'),
        ),
    ]
