# Generated by Django 2.2.2 on 2020-04-19 07:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import federation.models
import federation.validators
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Федерация',
                'verbose_name': 'Федерация',
            },
        ),
        migrations.CreateModel(
            name='FederationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, unique=True, verbose_name='Название структуры')),
                ('imageOld', models.ImageField(default='', upload_to=federation.models.FederationElement.user_directory_path, validators=[federation.validators.validate_image], verbose_name='Картинка к элементу структуры')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '320x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name='image')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Federation')),
            ],
            options={
                'verbose_name_plural': 'Структуры Федерации',
                'ordering': ['customOrder'],
                'verbose_name': 'Структура Федерация',
            },
        ),
        migrations.CreateModel(
            name='FederationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='', max_length=201, verbose_name='Должность')),
                ('imageOld', models.ImageField(default='', upload_to=federation.models.FederationStaff.user_directory_path, validators=[federation.validators.validate_image], verbose_name='Фото')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '320x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name='image')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.FederationElement', verbose_name='Структура')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['customOrder'],
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='FederationDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, default='', upload_to='documents/', validators=[federation.validators.validate_documents], verbose_name='Файл')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.Federation')),
            ],
            options={
                'verbose_name_plural': 'Документы',
                'ordering': ['customOrder'],
                'verbose_name': 'Документ',
            },
        ),
        migrations.AddIndex(
            model_name='federationstaff',
            index=models.Index(fields=['name'], name='federation__name_f53e93_idx'),
        ),
        migrations.AddIndex(
            model_name='federationstaff',
            index=models.Index(fields=['position'], name='federation__positio_6eb27b_idx'),
        ),
        migrations.AddIndex(
            model_name='federationstaff',
            index=models.Index(fields=['text'], name='federation__text_e383b0_idx'),
        ),
        migrations.AddIndex(
            model_name='federationelement',
            index=models.Index(fields=['title'], name='federation__title_e326cb_idx'),
        ),
    ]
