# Generated by Django 2.2.2 on 2020-04-19 15:19

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federationelement',
            options={'ordering': ['customOrder'], 'verbose_name': 'Структуру Федерация', 'verbose_name_plural': 'Структуры Федерации'},
        ),
        migrations.AlterField(
            model_name='federationelement',
            name='image',
            field=image_cropping.fields.ImageRatioField('imageOld', '320x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='federationstaff',
            name='image',
            field=image_cropping.fields.ImageRatioField('imageOld', '320x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name=''),
        ),
    ]
