# Generated by Django 2.2.2 on 2020-06-10 19:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_auto_20200419_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=301, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='federation',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='federation',
            name='map',
            field=models.CharField(blank=True, default='', max_length=1501, verbose_name='Ссылка на Яндекс-карту'),
        ),
        migrations.AddField(
            model_name='federation',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='federation',
            name='text',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='federation',
            name='work_time',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Режим работы'),
        ),
    ]
