# Generated by Django 2.2.2 on 2020-06-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_auto_20200610_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationelement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='federationelement',
            name='imageOld',
        ),
    ]
