# Generated by Django 2.2.2 on 2020-04-20 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import information.models
import information.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('fullname', models.CharField(default='', max_length=200, verbose_name='Полное имя')),
                ('image', models.ImageField(default='', upload_to=information.models.Player.user_directory_path, validators=[information.validators.validate_image], verbose_name='Фото')),
                ('position', models.CharField(choices=[('G', 'Вратарь'), ('D', 'Защитник'), ('M', 'Полузащитник'), ('F', 'Нападающий'), ('U', 'Универсал')], default='Универсал', max_length=25, verbose_name='Амплуа')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayersHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Пришел в команду')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Покинул команду')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Игровой номер')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Голы')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Голевые передачи')),
                ('yellowcards', models.PositiveIntegerField(default=0, verbose_name='Желтые карточки')),
                ('redcards', models.PositiveIntegerField(default=0, verbose_name='Красные карточки')),
            ],
            options={
                'ordering': ['-start'],
                'verbose_name': 'История Игрока',
                'verbose_name_plural': 'Истории Игроков',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата основания')),
                ('imageOld', models.ImageField(default='', upload_to=information.models.Team.user_directory_path, validators=[information.validators.validate_image], verbose_name='Лого')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения лого', hide_image_field=False, size_warning=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['title'], name='information_title_ae8c41_idx'),
        ),
        migrations.AddField(
            model_name='playershistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Player', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playershistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Team', verbose_name='Команда'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['fullname'], name='information_fullnam_5937e1_idx'),
        ),
    ]
