# Generated by Django 2.2.2 on 2020-04-20 15:58

from django.db import migrations, models
import information.models
import information.validators


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=information.models.Player.user_directory_path, validators=[information.validators.validate_image], verbose_name='Фото'),
        ),
    ]
