# Generated by Django 2.2.2 on 2020-04-20 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200420_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playershistory',
            name='end',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Покинул команду'),
        ),
        migrations.AlterField(
            model_name='playershistory',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Пришел в команду'),
        ),
    ]
