# Generated by Django 2.2.2 on 2020-04-20 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20200420_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playershistory',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Игровой номер'),
        ),
    ]
