# Generated by Django 2.2.2 on 2020-04-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20200420_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playershistory',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playershistory',
            name='team',
        ),
    ]
